[tool.poetry]
name = "fastapi-server"
version = "0.1.0"
description = "FastAPI server"
authors = ["moonlt932@example.com"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
fastapi = "^0.115.0"
uvicorn = {version = "^0.30.0", extras = ["standard"]}
pydantic = "^2.8.0"
python-multipart = "^0.0.9"
orjson = "^3.10.0"

# 공통 ML 러닝타임(가벼운 부분)
numpy = "1.26.4"
opencv-python-headless = "4.10.0.84"
retina-face = "0.0.17"
mtcnn = "1.0.0"

deepface = "0.0.95"
tensorflow = "2.15.1"  # DeepFace와 호환되는 안정적인 버전
pandas = ">=1.5.0,<3.0.0"  # TensorFlow 호환 범위
protobuf = ">=3.20.3,<4.24.0"  # TensorFlow 호환성을 위한 범위
soundfile = "^0.12.1"  # WAV 파일 저장용
scipy = "^1.11.0"  # 오디오 신호 처리용
ml-dtypes = "<0.5.0"
h5py = "3.10.0"
tf-keras = "2.15.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"